/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddendumReasonDTO } from './addendumReasonDTO';
import { ContractorDTO } from './contractorDTO';
import { Procurement } from './procurement';
import { SignatureDTO } from './signatureDTO';
import { SpecificationDTO } from './specificationDTO';


export interface AddendumDTO { 
    /**
     * id-документу
     */
    id?: number;
    /**
     * ЄДРПОУ-розпорядника
     */
    edrpou?: string;
    /**
     * Номер документу
     */
    documentNumber?: string;
    /**
     * Дата укладання документу
     */
    documentDate?: string;
    /**
     * Дата підписання (оприлюднення)
     */
    signDate?: string;
    /**
     * ЕЦП
     */
    signature?: SignatureDTO;
    /**
     * Вартість документу
     */
    amount?: number;
    /**
     * Валюта документу
     */
    currency?: string;
    /**
     * Еквівалент, грн. (для валютних документів)
     */
    currencyAmountUAH?: number;
    /**
     * Контрагенти
     */
    contractors?: Array<ContractorDTO>;
    /**
     * id-договору (\"батьківський\" договір для додаткової угоди)
     */
    parentId?: number;
    /**
     * строк дії дод.угоди з
     */
    fromDate?: string;
    /**
     * строк дії дод.угоди по
     */
    toDate?: string;
    /**
     * Безстроковий
     */
    noTerm?: boolean;
    /**
     * предмет додаткової угоди
     */
    subject?: string;
    /**
     * сума додаткової угоди
     */
    amountIncrease?: number;
    /**
     * з ПДВ/без ПДВ скоригована вартість основного договору
     */
    pdvInclude?: boolean;
    /**
     * сума ПДВ в скоригованій вартості основного договору
     */
    pdvAmount?: number;
    /**
     * Тип коригування вартості основного договору: 0: сума додаткової угоди зменшує вартість основного договору, 1: сума додаткової угоди збільшує вартість основного договору, 2: сума додаткової угоди не змінює вартість основного договору
     */
    correctionType?: number;
    /**
     * з ПДВ/без ПДВ сума додаткової угоди
     */
    isCorrectionWithPDF?: boolean;
    /**
     * сума ПДВ у сумі додаткової угоди
     */
    correctionVATValue?: number;
    /**
     * підстава укладення додаткової угоди: 0: зміна предмету, 1: зміна ціни, 2: зміна терміну, 99: інше
     */
    reasonTypes?: Array<AddendumReasonDTO>;
    /**
     * деталізація підстави \"99:інше\"
     */
    reasonOtherComment?: string;
    /**
     * Специфікації
     */
    specifications?: Array<SpecificationDTO>;
    /**
     * з ПДВ/ без ПДВ у ціні за одиницю специфікації
     */
    isCpvVat?: boolean;
    /**
     * Масив кодів за ДК 021:2015
     */
    procurementItems?: Array<Procurement>;
}
