/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AddressDTO { 
    city?: string;
    countryId?: number;
    countryName?: string;
    district?: string;
    districtCity?: string;
    house?: string;
    housing?: string;
    office?: string;
    regionId?: number;
    regionName?: string;
    street?: string;
}
