/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';


export interface ContractorDTO { 
    /**
     * Address
     */
    address?: AddressDTO;
    /**
     * Тип контрагента: 0: фізична особа, 1: фізична особа-підприємець, 2: юридична особа, -1: невизначений
     */
    contractorType?: number;
    /**
     * Ім'я керівника контрагента
     */
    firstName?: string;
    identifier?: string;
    /**
     * Прізвище керівника контрагента
     */
    lastName?: string;
    /**
     * По батькові керівника контрагента
     */
    middleName?: string;
    /**
     * Найменування контрагента
     */
    name?: string;
}
