/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocStat { 
    /**
     * Кількість внесених звітів
     */
    cntRep?: number;
    /**
     * К-ть внесених договорів
     */
    cntDoc?: number;
    /**
     * К-ть внесених додатків
     */
    cntAddDoc?: number;
    /**
     * К-ть внесених актів
     */
    cntAct?: number;
    /**
     * К-ть внесених штрафів
     */
    cntPeny?: number;
    /**
     * К-ть підписаних звітів
     */
    cntSignRep?: number;
    /**
     * К-ть підписаних договорів
     */
    cntSignCont?: number;
    /**
     * К-ть підписаних додатків
     */
    cntSignAddCont?: number;
    /**
     * К-ть підписаних актів
     */
    cntSignAct?: number;
    /**
     * К-ть підписаних штрафів
     */
    cntSignPeny?: number;
}
