/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FileDTO { 
    documentDate?: string;
    documentType?: FileDTO.DocumentTypeEnum;
    finishDate?: string;
}
export namespace FileDTO {
    export type DocumentTypeEnum = 'UNDEFINED' | 'CONTRACT' | 'ADDENDUM' | 'ACT' | 'PENY' | 'DELETED';
    export const DocumentTypeEnum = {
        UNDEFINED: 'UNDEFINED' as DocumentTypeEnum,
        CONTRACT: 'CONTRACT' as DocumentTypeEnum,
        ADDENDUM: 'ADDENDUM' as DocumentTypeEnum,
        ACT: 'ACT' as DocumentTypeEnum,
        PENY: 'PENY' as DocumentTypeEnum,
        DELETED: 'DELETED' as DocumentTypeEnum
    };
}
