/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { PersonDTO } from './personDTO';


export interface OrganizationGeneralDTO { 
    address?: AddressDTO;
    director?: PersonDTO;
    edrpou?: string;
    fullName?: string;
    koatuu?: string;
    shortName?: string;
}
