/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { OrganizationGeneralDTO } from './organizationGeneralDTO';
import { PersonDTO } from './personDTO';


export interface OrganizationDTO { 
    address?: AddressDTO;
    director?: PersonDTO;
    edrpou?: string;
    email?: string;
    generalDisposer?: OrganizationGeneralDTO;
    koatuu?: string;
    kopfg?: string;
    kved?: string;
    orgForm?: string;
    orgName?: string;
    orgType?: Array<string>;
    phone?: string;
    registrationDate?: string;
}
