/**
 * API spending.gov.ua
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentData } from './paymentData';


export interface TransactionDTO { 
    /**
     * Унікальний ідентифікатор
     */
    id?: number;
    /**
     * Код розрахункового документа
     */
    docVob?: string;
    /**
     * Тип розрахункового документа
     */
    docVobName?: string;
    /**
     * Номер розрахункового документа
     */
    docNumber?: string;
    /**
     * Дата складання
     */
    docDate?: string;
    /**
     * Дата валютування
     */
    docVDate?: string;
    /**
     * Дата оплати
     */
    transDate?: string;
    /**
     * Сума
     */
    amount?: number;
    /**
     * Сума в копійках
     */
    amountCop?: number;
    /**
     * Валюта
     */
    currency?: string;
    /**
     * Код платника
     */
    payerEdrpou?: string;
    /**
     * Найменування платника
     */
    payerName?: string;
    /**
     * Рахунок платника
     */
    payerAccount?: string;
    /**
     * Код банку платника
     */
    payerMfo?: string;
    /**
     * Найменування банку платника
     */
    payerBank?: string;
    /**
     * Код одержувача
     */
    reciptEdrpou?: string;
    /**
     * Найменування одержувача
     */
    reciptName?: string;
    /**
     * Рахунок одержувача
     */
    reciptAccount?: string;
    /**
     * Найменування банку одержувача
     */
    reciptBank?: string;
    /**
     * Код банку одержувача
     */
    reciptMfo?: string;
    /**
     * Призначення платежу
     */
    paymentDetails?: string;
    /**
     * Додатковий реквізит
     */
    docAddAttr?: string;
    /**
     * Регіон
     */
    regionId?: number;
    /**
     * Тип платіжної системи
     */
    paymentType?: string;
    /**
     * Додаткові дані визначеного типу платіжної системи
     */
    paymentData?: PaymentData;
    /**
     * Ідентифікатор джерела даних
     */
    sourceId?: number;
    /**
     * Джерело даних
     */
    sourceName?: string;
    /**
     * КЕКВ
     */
    kekv?: number;
    /**
     * КПКВК
     */
    kpk?: string;
    /**
     * Ідентифікатор договору про закупівлю
     */
    contractId?: string;
    /**
     * Ідентифікатор закупівлі (Prozorro)
     */
    contractNumber?: string;
    /**
     * Код бюджету
     */
    budgetCode?: string;
}
