export * from './budget.service';
import { BudgetService } from './budget.service';
export * from './dictionaries.service';
import { DictionariesService } from './dictionaries.service';
export * from './disposers.service';
import { DisposersService } from './disposers.service';
export * from './googleAnalyticStatistic.service';
import { GoogleAnalyticStatisticService } from './googleAnalyticStatistic.service';
export * from './map.service';
import { MapService } from './map.service';
export * from './pageableDisposers.service';
import { PageableDisposersService } from './pageableDisposers.service';
export * from './regions.service';
import { RegionsService } from './regions.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './statistic.service';
import { StatisticService } from './statistic.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export const APIS = [BudgetService, DictionariesService, DisposersService, GoogleAnalyticStatisticService, MapService, PageableDisposersService, RegionsService, ReportsService, StatisticService, TransactionsService];
